# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Testio' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Testio
  pod 'Alamofire', '~> 4.7'
  pod 'GSMessages'
  pod 'SAMKeychain'
  pod 'PromiseKit', '~> 6.0'
  pod 'RealmSwift'
end
