platform :ios, '11.0'

target 'ios-party' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  swift_version = "5.0"

  pod 'SnapKit'
  pod 'MaterialComponents/ActivityIndicator'
  pod 'SwiftKeychainWrapper'
  pod 'Just'
end
