# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testio' do
  use_frameworks!

  pod 'Alamofire'
  pod 'PromiseKit', '~> 6.8'
  pod 'PromiseKit/Alamofire'

end
