# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'testio' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testio
  pod 'Alamofire', '~> 4.7'
  pod 'SpinnerView'
  pod 'SwiftKeychainWrapper', '~> 3.0'
end
