# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Testio' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'RxSwift'
  pod 'RxOptional'
  pod 'Action'
  pod 'RealmSwift'

  # Pods for Testio

  target 'TestioTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
