# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Tesio App' do
  use_frameworks!

  pod 'Alamofire'
  pod 'SwiftKeychainWrapper'
  pod 'NVActivityIndicatorView'

end
